# Generated by Django 5.2.2 on 2025-06-15 03:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "social_type",
                    models.CharField(
                        choices=[("KAKAO", "Kakao"), ("GOOGLE", "Google")],
                        max_length=20,
                    ),
                ),
                ("social_id", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=100)),
                ("nickname", models.CharField(max_length=50)),
                ("profile_img", models.TextField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("남", "Male"), ("여", "Female")],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("birth_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "mbti",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ISTJ", "Istj"),
                            ("ISFJ", "Isfj"),
                            ("INTJ", "Intj"),
                            ("INFJ", "Infj"),
                            ("ISTP", "Istp"),
                            ("ISFP", "Isfp"),
                            ("INTP", "Intp"),
                            ("INFP", "Infp"),
                            ("ESTJ", "Estj"),
                            ("ESFJ", "Esfj"),
                            ("ENTJ", "Entj"),
                            ("ENFJ", "Enfj"),
                            ("ESTP", "Estp"),
                            ("ESFP", "Esfp"),
                            ("ENTP", "Entp"),
                            ("ENFP", "Enfp"),
                            ("선택안함", "None"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("dormant", "Dormant"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobSurvey",
            fields=[
                ("job_survey_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cognitive_type",
                    models.CharField(
                        choices=[
                            ("high_focus", "복잡한 문제 해결·전략적 사고 중심"),
                            ("multitask", "판단력·멀티태스킹·정보 처리 중심"),
                            ("physical", "반복적 업무·신체 활동 중심"),
                            ("none", "현재 일하지 않음 / 학생 / 은퇴 등"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "work_time_pattern",
                    models.CharField(
                        choices=[
                            ("regular_day", "낮 시간대, 규칙적 근무"),
                            ("shift_night", "교대/야간 등 불규칙 근무"),
                            ("flexible", "자유로운 시간대, 프리랜서 등"),
                            ("no_schedule", "일정 없음 / 학생 / 주부 등"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_surveys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserBlacklist",
            fields=[
                ("blacklist_id", models.AutoField(primary_key=True, serialize=False)),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("social_type", "social_id"), name="unique_social_type_id"
            ),
        ),
    ]
