# Generated by Django 5.2.2 on 2025-06-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("남", "Male"), ("여", "Female"), ("선택안함", "None")],
                max_length=5,
                null=True,
            ),
        ),
    ]
