# 작성자: 한율
# Generated by Django 5.2.2 on 2025-06-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("남", "Male"), ("여", "Female")],
                max_length=5,
                null=True,
            ),
        ),
    ]
