# Generated by Django 5.2.2 on 2025-06-14 16:13

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_birth_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_year",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, validators=[users.models.validate_birth_year]
            ),
        ),
    ]
