# Generated by Django 5.2.2 on 2025-06-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_img",
            field=models.ImageField(blank=True, null=True, upload_to="profile/"),
        ),
    ]
