# Generated by Django 5.2.2 on 2025-06-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0002_alter_user_birth_year_alter_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="social_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("social_type", "social_id"), name="unique_social_type_id"
            ),
        ),
    ]
