# Generated by Django 5.2.2 on 2025-07-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_profile_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="social_type",
            field=models.CharField(
                choices=[("KAKAO", "Kakao"), ("GOOGLE", "Google"), ("APPLE", "Apple")],
                max_length=20,
            ),
        ),
    ]
