# Generated by Django 5.2.2 on 2025-06-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_social_id_user_unique_social_type_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobsurvey",
            name="cognitive_type",
            field=models.CharField(
                choices=[
                    ("high_focus", "복잡한 문제 해결·전략적 사고 중심"),
                    ("multitask", "판단력·멀티태스킹·정보 처리 중심"),
                    ("physical", "반복적 업무·신체 활동 중심"),
                    ("none", "현재 일하지 않음 / 학생 / 은퇴 등"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobsurvey",
            name="work_time_pattern",
            field=models.CharField(
                choices=[
                    ("regular_day", "낮 시간대, 규칙적 근무"),
                    ("shift_night", "교대/야간 등 불규칙 근무"),
                    ("flexible", "자유로운 시간대, 프리랜서 등"),
                    ("no_schedule", "일정 없음 / 학생 / 주부 등"),
                ],
                max_length=20,
            ),
        ),
    ]
