# Generated by Django 5.2.2 on 2025-06-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_profile_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_completed_onboarding",
            field=models.BooleanField(default=False),
        ),
    ]
