# Generated by Django 5.2.2 on 2025-06-16 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CognitiveTestFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("estimated_duration_sec", models.PositiveIntegerField(default=60)),
                ("order", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CognitiveTestType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="CognitiveSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cognitive_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CognitiveResultSymbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                ("symbol_correct", models.IntegerField()),
                ("symbol_accuracy", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cognitive_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cognitive_statistics.cognitivesession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CognitiveResultSRT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                ("reaction_avg_ms", models.FloatField()),
                ("reaction_list", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cognitive_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cognitive_statistics.cognitivesession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CognitiveResultPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                ("pattern_correct", models.IntegerField()),
                ("pattern_time_sec", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cognitive_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cognitive_statistics.cognitivesession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CognitiveSessionProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problems",
                        to="cognitive_statistics.cognitivesession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CognitiveTestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("raw_scores", models.JSONField()),
                ("normalized_scores", models.JSONField()),
                ("average_score", models.FloatField()),
                ("total_duration_sec", models.PositiveIntegerField()),
                (
                    "test_format",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="cognitive_statistics.cognitivetestformat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cognitive_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CognitiveTestTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration_ms", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "test_format",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_records",
                        to="cognitive_statistics.cognitivetestformat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cognitive_times",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="cognitivetestformat",
            name="test_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formats",
                to="cognitive_statistics.cognitivetesttype",
            ),
        ),
    ]
