# Generated by Django 5.2.2 on 2025-06-16 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cognitive_statistics", "0001_initial"),
        ("cognitives", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cognitivesessionproblem",
            name="problem",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="cognitives.cognitiveproblem",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="cognitivesessionproblem",
            unique_together={("session", "problem")},
        ),
    ]
