# Generated by Django 5.2.2 on 2025-06-16 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cognitive_statistics", "0001_initial"),
        ("cognitives", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cognitivesessionproblem",
            name="problem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cognitives.cognitiveproblem",
            ),
        ),
        migrations.AddField(
            model_name="cognitivesessionproblem",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="problems",
                to="cognitive_statistics.cognitivesession",
            ),
        ),
        migrations.AddField(
            model_name="cognitivetestresult",
            name="test_format",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="cognitive_statistics.cognitivetestformat",
            ),
        ),
        migrations.AddField(
            model_name="cognitivetestresult",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cognitive_results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cognitivetesttime",
            name="test_format",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_records",
                to="cognitive_statistics.cognitivetestformat",
            ),
        ),
        migrations.AddField(
            model_name="cognitivetesttime",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cognitive_times",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cognitivetestformat",
            name="test_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formats",
                to="cognitive_statistics.cognitivetesttype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cognitivesessionproblem",
            unique_together={("session", "problem")},
        ),
    ]
