# Generated by Django 5.2.2 on 2025-06-26 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cognitive_statistics", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cognitiveresultsymbol",
            name="reaction_avg_ms",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="cognitivetestresult",
            name="cognitive_session",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="result",
                to="cognitive_statistics.cognitivesession",
            ),
        ),
    ]
