# Generated by Django 5.2.2 on 2025-06-19 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cognitive_statistics", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cognitivesession",
            name="test_format",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="cognitive_statistics.cognitivetestformat",
            ),
        ),
    ]
