# Generated by Django 5.2.2 on 2025-06-19 16:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SleepRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="sleep_record_id", primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField()),
                ("sleep_duration", models.IntegerField()),
                ("subjective_quality", models.IntegerField()),
                ("sleep_latency", models.IntegerField()),
                ("wake_count", models.IntegerField()),
                (
                    "disturb_factors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        help_text="수면 방해 요소 리스트",
                        size=None,
                    ),
                ),
                ("score", models.IntegerField()),
                ("memo", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sleep_record",
            },
        ),
    ]
