# Generated by Django 5.2.2 on 2025-06-15 03:14

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cognitive_statistics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SleepRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="sleep_record_id", primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField()),
                ("sleep_duration", models.IntegerField()),
                ("subjective_quality", models.IntegerField()),
                ("sleep_latency", models.IntegerField()),
                ("wake_count", models.IntegerField()),
                (
                    "disturb_factors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        help_text="수면 방해 요소 리스트",
                        size=None,
                    ),
                ),
                ("score", models.IntegerField()),
                ("memo", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sleep_record",
            },
        ),
        migrations.CreateModel(
            name="SleepScorePrediction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="sleep_score_prediction_id",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("record_date", models.DateTimeField(auto_now_add=True)),
                ("predicted_score", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sleep_score_prediction",
            },
        ),
        migrations.CreateModel(
            name="ContentRecommendation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="content_recommendation_id",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recommend_reason", models.TextField()),
                ("recommend_date", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cognitive",
                    models.ForeignKey(
                        db_column="cognitive_session_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cognitive_statistics.cognitivesession",
                    ),
                ),
            ],
            options={
                "db_table": "content_recommendation",
            },
        ),
    ]
