# Generated by Django 5.2.2 on 2025-06-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sleep_record", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sleeprecord",
            name="memo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
