# Generated by Django 5.2.2 on 2025-06-26 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sleep_record", "0002_alter_sleeprecord_memo"),
        ("sleep_record", "0002_initial"),
    ]

    operations = []
