# Generated by Django 5.2.2 on 2025-06-16 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cognitive_statistics", "0002_initial"),
        ("sleep_record", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentRecommendation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="content_recommendation_id",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recommend_reason", models.TextField()),
                ("recommend_date", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cognitive",
                    models.ForeignKey(
                        db_column="cognitive_session_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cognitive_statistics.cognitivesession",
                    ),
                ),
            ],
            options={
                "db_table": "content_recommendation",
            },
        ),
        migrations.CreateModel(
            name="SleepScorePrediction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="sleep_score_prediction_id",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("record_date", models.DateTimeField(auto_now_add=True)),
                ("predicted_score", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sleep_record",
                    models.ForeignKey(
                        db_column="sleep_record_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sleep_record.sleeprecord",
                    ),
                ),
            ],
            options={
                "db_table": "sleep_score_prediction",
            },
        ),
    ]
