# Generated by Django 5.2.2 on 2025-06-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentRecommendation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="content_recommendation_id",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recommend_reason", models.TextField()),
                ("recommend_date", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "content_recommendation",
            },
        ),
        migrations.CreateModel(
            name="SleepScorePrediction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="sleep_score_prediction_id",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("record_date", models.DateTimeField(auto_now_add=True)),
                ("predicted_score", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sleep_score_prediction",
            },
        ),
    ]
