# Generated by Django 5.2.2 on 2025-06-19 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai", "0001_initial"),
        ("cognitive_statistics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentrecommendation",
            name="cognitive",
            field=models.ForeignKey(
                db_column="cognitive_session_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="cognitive_statistics.cognitivesession",
            ),
        ),
    ]
