# Generated by Django 5.2.2 on 2025-06-19 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai", "0002_initial"),
        ("sleep_record", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sleepscoreprediction",
            name="sleep_record",
            field=models.ForeignKey(
                db_column="sleep_record_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="sleep_record.sleeprecord",
            ),
        ),
    ]
